### PR TITLE
Updated CONTROL events in vscp-protocol.xml

### PR DESCRIPTION
**Pull request by troky**

### CODE REVIEW

**Comment by BlueAndi** [comment]
Generating code is awesome. ;-) Thanks.
I guess you already have a VSCP event trace tool in mind, based on the xml model!?

**Comment by troky** [comment]
Well, that was manual change of xml... as I said - currently a lor faster :)
What do you mean by "event trace tool"? Something like event viewer with nice descriptions?

troky
    On Sunday, March 29, 2020, 12:20:10 PM GMT+2, Andreas Merkle <notifications@github.com> wrote:  
 
 


Generating code is awesome. ;-) Thanks.
I guess you already have a VSCP event trace tool in mind, based on the xml model!?

**Comment by BlueAndi** [comment]
Yes, I still think about a event viewer, which uses the .xml file as base. Original I created one in javascript, which uses an older .xml version of the protocol. This way we have another advantage of the protocol description.

**Comment by troky** [comment]
Well, the new event viewer is "work in progress". It is written from zero in C#. Currently it displays event class and type in text format and payload is still just raw hex bytes...
I have just finished migration to vscp-framework 1.0... it was a bumpy road, but it looks fine. I had to do "some" renaming :)
I have some time now to work on my vscp project so expect more pull requests and general vscp protocol updates.
Regards,troky
    On Tuesday, March 31, 2020, 07:00:11 PM GMT+2, Andreas Merkle <notifications@github.com> wrote:  
 
 


Yes, I still think about a event viewer, which uses the .xml file as base. Original I created one in javascript, which uses an older .xml version of the protocol. This way we have another advantage of the protocol description.

**Pull request merged**
